apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: securekube-app
type: Opaque
stringData:
  POSTGRES_DB: securekube
  POSTGRES_USER: securekube_user
  POSTGRES_PASSWORD: SecureKube2025
  DATABASE_URL: postgresql://securekube_user:SecureKube2025@postgres-svc:5432/securekube
