apiVersion: v1
kind: ConfigMap
metadata:
  name: falcosidekick-config
  namespace: falco
data:
  config.yaml: |
    kubernetes:
      enabled: true
      incluster: true
      action: "delete"
    alert:
      tags:
        - "kill_pod"
