apiVersion: v1
kind: ServiceAccount
metadata:
  name: remediation-sa
  namespace: securekube-security
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pod-remediator
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pod-remediator-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: pod-remediator
subjects:
  - kind: ServiceAccount
    name: remediation-sa
    namespace: securekube-security
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: remediation-engine
  namespace: securekube-security
spec:
  replicas: 1
  selector:
    matchLabels:
      app: remediation-engine
  template:
    metadata:
      labels:
        app: remediation-engine
    spec:
      serviceAccountName: remediation-sa
      containers:
        - name: remediation-engine
          image: securekube-remediation:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081
          readinessProbe:
            httpGet:
              path: /health
              port: 8081
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 6
          livenessProbe:
            httpGet:
              path: /health
              port: 8081
            initialDelaySeconds: 20
            periodSeconds: 15
            timeoutSeconds: 5
            failureThreshold: 6
          resources:
            requests:
              cpu: "10m"
              memory: "32Mi"
            limits:
              cpu: "50m"
              memory: "64Mi"
apiVersion: v1
kind: Service
metadata:
  name: remediation-svc
  namespace: securekube-security
spec:
  selector:
    app: remediation-engine
  ports:
    - port: 8081      # Change this to 8081
      targetPort: 8081 # Keep this at 8081